// AUTO-GENERATED by scripts/gen-pwa-icons.mjs — the in-gamut sRGB form of the
// seeded brand primary oklch(0.45 0.18 145). Keep in sync by re-running that script.
export const PWA_THEME_COLOR = "#006818"
